insert into Clients (FirstName, LastName, UserName, Password, AddressId, Email)
values('Jim', 'Morrison', 'jimson', 'thedoors', 1, 'jimson@rock.com')
insert into Clients (FirstName, LastName, UserName, Password, AddressId, Email)
values('Kanye', 'West', 'kanest', 'hiphop', 2, 'kanest@rnb.com')
insert into Clients (FirstName, LastName, UserName, Password, AddressId, Email)
values('Billy', 'Joel', 'biloel', 'pianoman', 3, 'biloel@rock.com')
insert into Clients (FirstName, LastName, UserName, Password, AddressId, Email)
values('Whitney', 'Houston', 'whiton', 'whitney', 4, 'whiton@soul.com')
insert into Clients (FirstName, LastName, UserName, Password, AddressId, Email)
values('Prince', 'Nelson', 'prison', 'purplerain', 5, 'prison@soul.com')