insert into Categories values ('Dog')
insert into Categories values ('Cat')
insert into Categories values ('Rabbit')
insert into Categories values ('Bearded Dragon')
insert into Categories values ('Snake')
insert into Categories values ('Penguin')