insert into Shots values('Parvo')
insert into Shots values('Dog Cough')
insert into Shots values('Rabies')
insert into Shots values('FVRCP')
insert into Shots values('Myxomatosis')
insert into Shots values('GTI')
insert into Shots values('Bird Flu')