insert into Rooms (RoomNumber, AnimalId)
values (1, 7)
insert into Rooms (RoomNumber, AnimalId)
values (2, 8)
insert into Rooms (RoomNumber, AnimalId)
values (3, 9)
insert into Rooms (RoomNumber, AnimalId)
values (4, 10)
insert into Rooms (RoomNumber, AnimalId)
values (5, 11)
insert into Rooms (RoomNumber, AnimalId)
values (6, 12)
insert into Rooms (RoomNumber)
values (7)
insert into Rooms (RoomNumber)
values (8)
insert into Rooms (RoomNumber)
values (9)
insert into Rooms (RoomNumber)
values (10)