insert into Rooms values(1,13)
insert into Rooms values(2,14)
insert into Rooms values(3,15)
insert into Rooms values(4,16)
insert into Rooms values(5,17)
insert into Rooms values(6,18)
insert into Rooms (RoomNumber) values(7)
insert into Rooms (RoomNumber) values(8)
insert into Rooms (RoomNumber) values(9)
insert into Rooms (RoomNumber) values(10)